version: '3.7'

services:
  postgres:
    image: timescale/timescaledb
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: metrics_db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgres/data
  app:
    build:
      context: ./docker/dev
      dockerfile: Dockerfile
    container_name: metrics_app
    ports:
      - 4000:4000
    depends_on:
      - postgres
    volumes:
      - .:/workspace
    command: sleep infinity
